// src/config/swagger.js
import swaggerJsdoc from 'swagger-jsdoc';

// Minimal, relative; we’ll override to absolute http at render time.
const swaggerDefinition = {
  openapi: '3.0.3',
  info: {
    title: 'ASL API',
    version: '1.0.0',
    description: 'Autogenerated Swagger docs via swagger-jsdoc',
  },
  servers: [
    { url: '/', description: 'Current Origin' },
  ],
  components: {
    securitySchemes: {
      // add bearer later if needed
    },
  },
};

export const swaggerOptions = {
  definition: swaggerDefinition,
  apis: ['src/routes/**/*.js', 'src/controllers/**/*.js'],
};
