import swaggerJsdoc from 'swagger-jsdoc';
import { env } from './env.js';

const swaggerDefinition = {
  openapi: '3.0.3',
  info: {
    title: 'ASL API',
    version: '1.0.0',
    description: 'Autogenerated Swagger docs via swagger-jsdoc',
  },
  servers: [
    { url: "/", description: 'Current Origin' }, 
    { url: "https://learnasl.vercel.app/", description: 'Production' }, 
    { url: `http://localhost:${env.port}`, description: 'Local HTTP' },
    { url: `https://localhost:${env.httpsPort}`, description: 'Local HTTPS' },
  ],
  components: {
    securitySchemes: {
      // Add bearer if you want later
    },
  },
};

export const swaggerOptions = {
  definition: swaggerDefinition,
  apis: ['src/routes/**/*.js', 'src/controllers/**/*.js'], // JSDoc sources
};
